### ISSUE TITLE
Main Page

### ISSUE THREAD

**Issue by twill81** [tillwilling/capstone-project#1]
## Value statement
**As a** user
**I want** to see pictures of locations with description
**so that** I can see my opportunities

## Description (Text, Scribble, Wireframe, Design)
![userstory1_mainscreen](https://user-images.githubusercontent.com/82399378/120526517-90d30480-c3d9-11eb-8503-1eea1c0cd8b6.jpg)

## Acceptance criteria
- [x] locations must be shown as a list
- [x] list must be scrollable

## Tasks
- [x] Create feature branch
- [x] Create list of locations (images)
- [x] Render locations as Images
- [x] Style image-list to be shown on top of each other

## Complexity
(low)
