### ISSUE TITLE
Filter-Function location

### ISSUE THREAD

**Issue by twill81** [tillwilling/capstone-project#2]
## Value statement
**As a** user
**I want** to filter the shown content
**so that** i only see locations where i search one

## Description (Text, Scribble, Wireframe, Design)
![userstory2_where](https://user-images.githubusercontent.com/82399378/120533462-0ababc00-c3e1-11eb-950a-c5f588d28419.jpg)

## Acceptance criteria
- [ ] needs text input with submit function
- [ ] Nav-Bar must be clickable
- [ ] Device needs to be able to locate
- [ ] after clicking Nav-Bar show nearby locations
- [ ] set Radius to search "nearby" to 50km
- [ ] empty input should set to default

## Tasks
- [ ] create feature branch
- [ ] integrate form input="text"
- [ ] style input and set to top like in scribble
- [ ] create filter function for locations after submit input
- [ ] integrate Nav-Bar and set to fixed bottom
- [ ] insert Text "In meiner Nähe" in Nav-Bar
- [ ] make Nav-Bar clickable
- [ ] create submit-function for "click" on Nav-Bar to search locations nearby (max 50km radius)

## Complexity
(medium)
