### ISSUE TITLE
Set Bookmarks

### ISSUE THREAD

**Issue by twill81** [tillwilling/capstone-project#3]
## Value statement
**As a** user
**I want** to save bookmarked locations
**so that** I can get a list of my favorites

## Description (Text, Scribble, Wireframe, Design)
![userstory3_bookmark](https://user-images.githubusercontent.com/82399378/120535812-b6fda200-c3e3-11eb-8d5a-e02f138f69ee.jpg)

Buttons in Nav-Bar from left to right: nearby, mainpage, favorites

## Acceptance criteria
- [ ] every image needs a clickable icon to set bookmark
- [ ] bookmarks need toggle
- [ ] bookmarked status must be saved to not forget after reload
- [ ] bookmarked elements must be shown in "Favorites"
- [ ] bookmarked elements in "Favorites" must be un-bookmarkable to get out of list
- [ ] "Nearby-Button" must filter to nearby locations
- [ ] "Mainpage-Button" must reset filter
- [ ] "Favorites-Button" must lead to Favorites-Page (Userstory4 - Favorites)

## Tasks
- [ ] create feature branch
- [ ] create icons for bookmark
- [ ] make icons clickable with togglefunction
- [ ] create function to save bookmarked elements in local storage
- [ ] createButtons for Nav-Bar with icons
- [ ] make nearby and mainpage buttons functionable

## Complexity
(medium)
