### ISSUE TITLE
Favorites-Page

### ISSUE THREAD

**Issue by twill81** [tillwilling/capstone-project#4]
## Value statement
**As a** role
**I need** action
**so that** benefit

## Description (Text, Scribble, Wireframe, Design)
![userstory4_favorites](https://user-images.githubusercontent.com/82399378/120537919-22e10a00-c3e6-11eb-9730-739a8a6ecb25.jpg)

On this site, we have only 2 buttons in the Nav-Bar for "nearby" and "mainpage"

## Acceptance criteria
- [ ] only bookmarked "locations" will be shown
- [ ] only 2 buttons will be shown in Nav-Bar
- [ ] by clicking on the bookmark-icon, element will be deleted out of localstorage but should stay till page-reload
- [ ] filterfunctions still usable
- [ ] mainpage-button leads to mainpage

## Tasks
- [ ] create feature branch
- [ ] create favorites-page
- [ ] render bookmarked content from local storage
- [ ] build new Nav-Bar with only two buttons (nearby and mainpage)

## Complexity
(medium)
