### ISSUE TITLE
Add Game Page

### ISSUE THREAD

**Issue by twill81** [tillwilling/capstone-project#6]
## Value statement
**As a** user
**I want** to add different games
**so that** i have a list of games I own

## Description (Text, Scribble, Wireframe, Design)
![Bildschirmfoto 2021-06-14 um 11 36 21](https://user-images.githubusercontent.com/82399378/121871861-e4601f00-cd04-11eb-92b7-2dbbce52c356.png)

## Acceptance criteria
- [x] needs text input field
- [x] needs a submit button called "Add game"
- [x] after clicking "Add game" show game in a list

## Tasks
- [x] create feature branch
- [x] integrate form input="text"
- [x] integrate submit-button "Add game"
- [x] write list component for submitted games
- [x] style input field
- [x] style button
- [x] style list

## Complexity
(low)
