### ISSUE TITLE
detail page

### ISSUE THREAD

**Issue by twill81** [tillwilling/capstone-project#7]
## Value statement
**As a** user
**I want** to see all the games I added
**so that** i can choose one by clicking on it, to see further informations

## Description (Text, Scribble, Wireframe, Design)
![Bildschirmfoto 2021-06-14 um 13 49 44](https://user-images.githubusercontent.com/82399378/121887751-6d805180-cd17-11eb-8591-37361c8b2f4d.png)

## Acceptance criteria
- [ ] games page needs a list of all the games I added
- [ ] games must be clickable
- [ ] after clicking on a game, show page of further informations to the game

## Tasks
- [ ] create a page with list of all my added games
- [ ] style list (image or just the name or both)
- [ ] create "Add a game" button
- [ ] link "Add a game" button to "Add game" page
- [ ] create detail page for a single game (name of game, description)
- [ ] create "Back" button on detail page to get back to game list
- [ ] link list-items to detail page of a game

## Complexity
(medium)
