### ISSUE TITLE
add RAWG API and autocompletion to text-input OR drop-down menu

### ISSUE THREAD

**Issue by twill81** [tillwilling/capstone-project#8]
## Value statement
**As a** user
**I want** to add different games with autocomplete OR choose a game from a list of all games from database
**so that** i have a list of games I own

## Description (Text, Scribble, Wireframe, Design)
![Bildschirmfoto 2021-06-14 um 12 05 41](https://user-images.githubusercontent.com/82399378/121879143-d0202000-cd0c-11eb-83bb-e74578d1d67f.png)

## Acceptance criteria
- [ ] needs text input field with autocomplete OR a drop-down-menu
- [ ] needs the RAWG API
- [ ] needs a submit button called "Add game"
- [ ] after clicking "Add game" show game in a list

## Tasks
- [ ] implement RAWG API
- [ ] add autocomplete function to text-input OR refactor it into drop-down menu

## Complexity
(medium)
