### ISSUE TITLE
add reddit

### ISSUE THREAD

**Issue by twill81** [tillwilling/capstone-project#9]
## Value statement
**As a** user
**I want** to see if there are free giveaways to games i own

## Description (Text, Scribble, Wireframe, Design)
![Bildschirmfoto 2021-06-14 um 13 53 42](https://user-images.githubusercontent.com/82399378/121888201-ff885a00-cd17-11eb-9287-c4f58bd38bbc.png)

## Acceptance criteria
- [ ] implement reddit from RAWG API
- [ ] needs a reddit section on detail page
- [ ] must be clickable to get to the reddit discussion

## Tasks
- [ ] integrate section for reddit
- [ ] style section
- [ ] link to reddit discussions

## Complexity
(medium)
